image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - init: |
      ./tools/update.sh
      ./tools/build_writefile.sh
    command: node headless.js
vscode:
  extensions:
    - dbaeumer.vscode-eslint
