image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: notify

tasks:
  - init: |
      yarn update
      ./tools/build_writefile.sh
    command: yarn dev-headless
vscode:
  extensions:
    - dbaeumer.vscode-eslint
